// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.GlitchenAutoTesting.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5506.GlitchenAutoTesting.Robot;

/**
 *
 */
public class Turn extends Command {

    private double degToTurn;
	private double distanceAngle;
	private boolean turningLeft = false;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Turn(double degToTurn) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    	this.degToTurn = degToTurn;
    	distanceAngle = degToTurn*(0.195258710066866);
    	if(degToTurn<0)
    		turningLeft = true;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	//Robot.chassis.resetEncoders();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if(turningLeft)
    		Robot.chassis.tankDrive(0.5, 0);
    	else
    		Robot.chassis.tankDrive(0,  0.5);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	/*if(turningLeft)
    		if(Robot.chassis.getRightRotations()>=distanceAngle)
    			return true;
    		else
    			return false;
    	else
    		if(Robot.chassis.getLeftRotations()>=distanceAngle)
    			return true;
    		else*/
    			return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.chassis.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
